### PR TITLE
Fix generation when a companion object exists

### LINKED ISSUE #17: Reuse existing companion object
## Minimized code

```Scala
import dataclass.data

@data class Foo(bar: String)

object Foo {
  val baz = "baz"
}
```

## Output

```scala
import dataclass.data

@data final class Foo private (val bar: String)
    extends Product
    with Serializable {

  ...

}

object Foo {
  def apply(bar: String): Foo = new Foo(bar)
}

object Foo {
  val baz = "baz"
}
```

## Expectation

```scala
import dataclass.data

@data final class Foo private (val bar: String)
    extends Product
    with Serializable {

  ...

}

object Foo {
  val baz = "baz"

  def apply(bar: String): Foo = new Foo(bar)
}
```

### PR DESCRIPTION
**Pull request by andrelfpinto**
Fixes #17

### CODE REVIEW

File: rules/src/main/scala/fix/GenerateDataClass.scala [hunk 1]
```diff
@@ -231,18 +231,41 @@ class GenerateDataClass(config: Configuration) extends SemanticRule("GenerateDat
...
-    val block = stats.mkString("\n")
-    val code =
-      s"""|object ${cls.name.value} {
-          |$block
-          |}
-          |""".stripMargin
-    Patch.addRight(cls, code)
+    objOpt match {
+      case Some(obj) => {
+        val block = (obj.templ.stats ::: stats).mkString("\n")
```
Comment (hamnis) [inline rules/src/main/scala/fix/GenerateDataClass.scala:236]: we should remove any apply methods if they exist in the existing companion

File: rules/src/main/scala/fix/GenerateDataClass.scala [hunk 2]
```diff
@@ -161,7 +161,7 @@ class GenerateDataClass(config: Configuration) extends SemanticRule("GenerateDat
     Patch.replaceTree(cls, code)
   }
 
-  def generateCompanion(cls: Defn.Class) = {
+  def generateCompanion(cls: Defn.Class, objOpt: Option[Defn.Object]) = {
```
Comment (hamnis) [inline rules/src/main/scala/fix/GenerateDataClass.scala:164]: maybeCompanion?

**Review by hamnis — APPROVED** [review]
